name: Build, Push and Deploy to AKS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login via Service Principal
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.SUBSCRIPTION  }}
        auth-type: IDENTITY

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        resource-group: veiculo
        cluster-name: veiculo

    - name: Login to Azure Container Registry (ACR)
      run: |
        az acr login --name veiculo

    - name: Build Docker image
      run: |
        docker build -t veiculo.azurecr.io/veiculo-venda:latest .

    - name: Push Docker image to ACR
      run: |
        docker push veiculo.azurecr.io/veiculo-venda:latest

    - name: Deploy to AKS
      run: |
        kubectl apply -f ./deploy/deployment.yaml
        kubectl apply -f ./deploy/service.yaml
