name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: |
        cd src 
        dotnet restore Pagamento-Veiculo.API.sln
    - name: Build
      run: |
        cd src 
        dotnet build Pagamento-Veiculo.API.sln --no-restore
    - name: Test
      run: |
        cd src 
        dotnet test Pagamento-Veiculo.API.sln --no-build --verbosity normal
